# Site

title: Fify Site
url: "https://helpful-cauliflower.cloudvent.net"

# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: nested
  sourcemap: true

exclude: ['README.md']

collections:
  courses:
    output: true;
  events:
    output: true;
  lectures:
    output: true;
  fiftyfabalumni:
    output: false;
